version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=https://iot-building-simulator-1.onrender.com
      - REACT_APP_WS_URL=ws://iot-building-simulator-1.onrender.com
    volumes:
      - ./src:/app/src 